# Crear base de datos Intact - sujetos sin amputación

In: dataset `features_mixed_global_withRest_200ms.csv`.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')
sns.set_theme(style='whitegrid')
%matplotlib inline

## Crear dataset Sujetos NO amputados

In [2]:
# Dolor de cabeza... cómo se unen según sujeto, estimulo, base de datos y canal
meta_cols = ['subject', 'stimulus', 'origin_db','repetition']
# Features
features = ['VAR_STD', 'Range', 'Energy', 'Peak_to_Peak', 'VAR', 'Max', 'MNF', 'SSC']
# Channel 1..8 × features
signal_cols = [f'Channel {ch}_{feat}' for ch in range(1, 9) for feat in features]
# Estímulos de interés (nos falta el reposo)
selected_stimuli = [0, 22, 25, 27, 30, 31, 37, 40]

print(f'Features       : {len(features)}')
print(f'Canales        : 8  →  columnas de señal: {len(signal_cols)}')
print(f'Estímulos selec: {selected_stimuli}')

# dataset que contiene todas las bases de datos
path_dataset = '../data/master/features_mixed_global_withRest_200ms.csv'
df_raw_intact = pd.read_csv(path_dataset)
print(f'Shape dataset: {df_raw_intact.shape}')
df_raw_intact.head(10)

Features       : 8
Canales        : 8  →  columnas de señal: 64
Estímulos selec: [0, 22, 25, 27, 30, 31, 37, 40]
Shape dataset: (881072, 216)

,origin_db,subject_global,subject,stimulus,repetition,window_size_samples,window_size_ms,window_index,Channel 1_MAV,Channel 1_IAV,...,Channel 8_VAR_STD,Channel 8_Skewness,Channel 8_Kurtosis,Channel 8_Mean,Channel 8_Median,Channel 8_Max,Channel 8_Min,Channel 8_Range,Channel 8_Energy,Channel 8_Peak_to_Peak
0,NinaProDB1,1,1,18,1,20,200,0,0.413844,8.276885,...,0.001424,0.097531,-1.213684,0.587019,0.585003,0.670843,0.510164,0.160679,6.940010,0.0268
1,NinaProDB1,1,1,18,1,20,200,1,0.254527,5.090548,...,0.001615,0.481123,-1.038822,0.455558,0.450462,0.503277,0.425394,0.077883,4.162480,0.0317
2,NinaProDB1,1,1,18,1,20,200,2,0.163912,3.278237,...,0.001723,0.767104,-0.706780,0.443536,0.436857,0.485417,0.424243,0.061174,3.941990,0.0390
3,NinaProDB1,1,1,18,1,20,200,3,0.156298,3.125970,...,0.003003,0.208083,-1.181009,0.585812,0.580298,0.697925,0.492648,0.205277,6.942215,0.0561
4,NinaProDB1,1,1,18,1,20,200,4,0.213209,4.264171,...,0.128570,0.044826,-1.216617,0.854279,0.852605,1.002573,0.711739,0.290833,14.753204,0.6275
5,NinaProDB1,1,1,18,1,20,200,5,0.295198,5.903957,...,1.030834,-0.086051,-1.211857,1.160887,1.163924,1.292959,1.018383,0.274575,27.093463,1.0571
6,NinaProDB1,1,1,18,1,20,200,6,0.364305,7.286102,...,0.717084,-0.286101,-1.147822,1.398396,1.404534,1.470541,1.305149,0.165392,39.161502,0.7128
7,NinaProDB1,1,1,18,1,20,200,7,0.402680,8.053609,...,0.248849,-1.178866,0.364741,1.495203,1.497913,1.502598,1.475400,0.027197,44.713862,0.3686
8,NinaProDB1,1,1,18,1,20,200,8,0.415609,8.312171,...,0.105987,-0.301074,-1.152247,1.444945,1.449119,1.490469,1.385033,0.105437,41.778426,0.2173
9,NinaProDB1,1,1,18,1,20,200,9,0.419798,8.395968,...,0.061534,-0.055837,-1.216418,1.295727,1.296921,1.377268,1.210038,0.167230,33.630218,0.1904

Filtrando solo los estimulos de interés

In [4]:
df_intact = df_raw_intact[df_raw_intact['stimulus'].isin(selected_stimuli)][meta_cols + signal_cols].copy().reset_index(drop=True)
# Solo las bases de datos 1, 2, 4 y 5 que son NO amputados
df_intact = df_intact[df_intact['origin_db'].isin(['NinaProDB1', 'NinaProDB2', 'NinaProDB4', 'NinaProDB5'])]
print(df_intact['origin_db'].unique())
# guardar database como database_intact.csv
df_intact.to_csv('../data/master/database_intact.csv', index=False)
df_intact.head(30)

<ArrowStringArray>
['NinaProDB1', 'NinaProDB2', 'NinaProDB4', 'NinaProDB5']
Length: 4, dtype: str

,subject,stimulus,origin_db,repetition,Channel 1_VAR_STD,Channel 1_Range,Channel 1_Energy,Channel 1_Peak_to_Peak,Channel 1_VAR,Channel 1_Max,...,Channel 7_MNF,Channel 7_SSC,Channel 8_VAR_STD,Channel 8_Range,Channel 8_Energy,Channel 8_Peak_to_Peak,Channel 8_VAR,Channel 8_Max,Channel 8_MNF,Channel 8_SSC
0,1,22,NinaProDB1,1,0.001033,0.040034,9.149888,0.0611,1.477702e-04,0.695626,...,5.961012,2,0.000932,0.071187,7.951489,0.0317,0.000467,0.665271,3.388667,4
1,1,22,NinaProDB1,1,0.000046,0.048506,7.932059,0.0122,2.169982e-04,0.653253,...,5.172572,4,0.000950,0.076264,6.109683,0.0342,0.000537,0.590169,4.875131,3
2,1,22,NinaProDB1,1,0.000000,0.055218,6.613127,0.0000,2.813390e-04,0.601996,...,8.095824,3,0.000486,0.072910,4.477883,0.0244,0.000493,0.509871,3.115516,3
3,1,22,NinaProDB1,1,0.000048,0.058243,5.303784,0.0098,3.132917e-04,0.543751,...,11.251693,4,0.005782,0.054283,3.274406,0.1123,0.000275,0.433467,7.660429,0
4,1,22,NinaProDB1,1,0.000004,0.055119,4.134773,0.0025,2.810018e-04,0.482461,...,3.711943,4,0.002377,0.019837,2.653012,0.0537,0.000039,0.377117,2.589679,4
5,1,22,NinaProDB1,1,0.000046,0.043684,3.229690,0.0098,1.770469e-04,0.424665,...,3.950488,2,0.002755,0.022272,2.670651,0.0512,0.000049,0.379607,3.427735,4
6,1,22,NinaProDB1,1,0.000160,0.023916,2.672116,0.0245,5.377954e-05,0.379140,...,10.654974,4,0.015981,0.057321,3.343680,0.1880,0.000307,0.439152,9.079539,1
7,1,22,NinaProDB1,1,0.008077,0.003245,2.492335,0.1319,9.742220e-07,0.355155,...,5.442071,6,0.120545,0.071460,4.586641,0.4052,0.000475,0.514219,4.342650,1
8,1,22,NinaProDB1,1,0.006998,0.023225,2.679739,0.0684,5.072735e-05,0.379052,...,7.959532,1,0.079875,0.061419,6.059224,0.2857,0.000350,0.579318,3.258679,4
9,1,22,NinaProDB1,1,0.039785,0.037776,3.185912,0.2172,1.326119e-04,0.418522,...,1.830359,3,0.034738,0.036814,7.260615,0.1733,0.000126,0.618780,2.803425,4
10,1,22,NinaProDB1,1,0.018625,0.040929,3.899136,0.1270,1.553876e-04,0.461624,...,3.141525,6,0.032235,0.011456,7.873035,0.1758,0.000013,0.631463,2.588512,2
11,1,22,NinaProDB1,1,0.053042,0.033214,4.632598,0.2637,1.023794e-04,0.496870,...,5.527030,1,0.051302,0.006237,7.922575,0.2050,0.000004,0.631532,1.711881,3
12,1,22,NinaProDB1,1,0.102259,0.018905,5.179858,0.4003,3.325155e-05,0.517175,...,1.898252,5,0.038338,0.015422,7.623977,0.1538,0.000022,0.624664,1.978974,1
13,1,22,NinaProDB1,1,0.021044,0.005151,5.432700,0.1343,2.547461e-06,0.522922,...,1.575899,6,0.023834,0.019530,7.170583,0.1171,0.000035,0.608296,1.678606,4
14,1,22,NinaProDB1,1,0.008599,0.002006,5.453047,0.1196,4.236123e-07,0.522934,...,3.512468,6,0.037016,0.022152,6.654642,0.2124,0.000045,0.587668,4.508042,0
15,1,22,NinaProDB1,1,0.017732,0.001856,5.400692,0.1953,3.418478e-07,0.520777,...,2.255430,6,0.028437,0.024934,6.095589,0.2075,0.000057,0.564278,5.240075,5
16,1,22,NinaProDB1,1,0.043782,0.001334,5.394350,0.1831,1.819343e-07,0.520232,...,2.869339,5,0.083935,0.026406,5.508034,0.3174,0.000065,0.537966,4.368714,6
17,1,22,NinaProDB1,1,0.037810,0.003128,5.447520,0.2271,9.195717e-07,0.523499,...,3.643198,6,0.028088,0.021828,4.972931,0.2198,0.000045,0.510215,4.794209,1
18,1,22,NinaProDB1,1,0.015327,0.002741,5.514944,0.1489,6.976897e-07,0.526407,...,4.344929,3,0.034073,0.007252,4.656545,0.2466,0.000005,0.487535,6.704587,3
19,1,22,NinaProDB1,1,0.021405,0.001570,5.562981,0.2002,2.295822e-07,0.528092,...,5.216703,5,0.031372,0.015474,4.736803,0.2050,0.000023,0.496147,3.760685,5
20,1,22,NinaProDB1,1,0.014234,0.000274,5.582154,0.2368,7.803481e-09,0.528406,...,10.451749,3,0.143111,0.035272,5.289284,0.5932,0.000116,0.532837,8.566792,1
21,1,22,NinaProDB1,1,0.013913,0.004119,5.543598,0.0879,1.571047e-06,0.528058,...,8.015252,4,0.070961,0.039308,6.166927,0.2417,0.000145,0.574289,3.460295,7
22,1,22,NinaProDB1,1,0.037745,0.013430,5.361232,0.2880,1.666687e-05,0.523528,...,5.359457,3,0.118858,0.020590,6.929915,0.4248,0.000041,0.596653,5.612411,3
23,1,22,NinaProDB1,1,0.002408,0.027917,4.927899,0.0732,7.203805e-05,0.509045,...,5.918525,2,0.021075,0.017644,6.996594,0.1539,0.000031,0.596963,4.034330,4
24,1,22,NinaProDB1,1,0.000546,0.044627,4.201655,0.0342,1.840550e-04,0.479221,...,2.827232,8,0.027179,0.063173,6.033744,0.1660,0.000372,0.577192,3.255199,2
25,1,22,NinaProDB1,1,0.000586,0.059384,3.255603,0.0415,3.259367e-04,0.431821,...,6.455393,5,0.038242,0.099091,4.285483,0.3003,0.000912,0.509584,6.049025,2
26,1,22,NinaProDB1,2,0.000004,0.067664,2.259034,0.0025,4.234953e-04,0.369018,...,5.212160,4,0.000827,0.106758,2.478475,0.0244,0.001061,0.404762,1.884856,3
27,1,22,NinaProDB1,2,0.000000,0.064839,1.408100,0.0000,3.896610e-04,0.297753,...,8.343648,4,0.001321,0.073396,1.280877,0.0391,0.000508,0.292889,3.002070,3
28,1,22,NinaProDB1,2,0.000000,0.047319,0.838683,0.0000,2.089266e-04,0.229829,...,7.362699,4,0.001009,0.010761,0.885178,0.0269,0.000012,0.217263,2.227003,3
29,1,22,NinaProDB1,2,0.000004,0.015252,0.580813,0.0025,2.350529e-05,0.180756,...,7.280579,3,0.001573,0.090587,1.340782,0.0390,0.000772,0.309480,2.257712,2